# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/downloads/TEMPered

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/PCsensor/TEMPered

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/PCsensor/TEMPered/CMakeFiles /opt/PCsensor/TEMPered/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/PCsensor/TEMPered/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tempered-shared

# Build rule for target.
tempered-shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tempered-shared
.PHONY : tempered-shared

# fast build rule for target.
tempered-shared/fast:
	$(MAKE) -f libtempered/CMakeFiles/tempered-shared.dir/build.make libtempered/CMakeFiles/tempered-shared.dir/build
.PHONY : tempered-shared/fast

#=============================================================================
# Target rules for targets named tempered-util-shared

# Build rule for target.
tempered-util-shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tempered-util-shared
.PHONY : tempered-util-shared

# fast build rule for target.
tempered-util-shared/fast:
	$(MAKE) -f libtempered-util/CMakeFiles/tempered-util-shared.dir/build.make libtempered-util/CMakeFiles/tempered-util-shared.dir/build
.PHONY : tempered-util-shared/fast

#=============================================================================
# Target rules for targets named hid-query

# Build rule for target.
hid-query: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hid-query
.PHONY : hid-query

# fast build rule for target.
hid-query/fast:
	$(MAKE) -f utils/CMakeFiles/hid-query.dir/build.make utils/CMakeFiles/hid-query.dir/build
.PHONY : hid-query/fast

#=============================================================================
# Target rules for targets named tempered-exe

# Build rule for target.
tempered-exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tempered-exe
.PHONY : tempered-exe

# fast build rule for target.
tempered-exe/fast:
	$(MAKE) -f utils/CMakeFiles/tempered-exe.dir/build.make utils/CMakeFiles/tempered-exe.dir/build
.PHONY : tempered-exe/fast

#=============================================================================
# Target rules for targets named enumerate

# Build rule for target.
enumerate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enumerate
.PHONY : enumerate

# fast build rule for target.
enumerate/fast:
	$(MAKE) -f examples/CMakeFiles/enumerate.dir/build.make examples/CMakeFiles/enumerate.dir/build
.PHONY : enumerate/fast

#=============================================================================
# Target rules for targets named read-all

# Build rule for target.
read-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 read-all
.PHONY : read-all

# fast build rule for target.
read-all/fast:
	$(MAKE) -f examples/CMakeFiles/read-all.dir/build.make examples/CMakeFiles/read-all.dir/build
.PHONY : read-all/fast

#=============================================================================
# Target rules for targets named read-repeat

# Build rule for target.
read-repeat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 read-repeat
.PHONY : read-repeat

# fast build rule for target.
read-repeat/fast:
	$(MAKE) -f examples/CMakeFiles/read-repeat.dir/build.make examples/CMakeFiles/read-repeat.dir/build
.PHONY : read-repeat/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... tempered-shared"
	@echo "... tempered-util-shared"
	@echo "... hid-query"
	@echo "... tempered-exe"
	@echo "... enumerate"
	@echo "... read-all"
	@echo "... read-repeat"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

